// <auto-generated />
using System;
using System.Collections.Generic;
using GestaoEpiEpc.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoEpiEpc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GestaoEpiDbContext))]
    [Migration("20260929231914_ApiMobile")]
    partial class ApiMobile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_cargo");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_cargo_nome");

                    b.ToTable("cargo", (string)null);
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.CargoItemPermitido", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cargo_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.HasKey("Id")
                        .HasName("pk_cargo_item_permitido");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_cargo_item_permitido_item_id");

                    b.HasIndex("CargoId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_cargo_item_permitido_cargo_id_item_id");

                    b.ToTable("cargo_item_permitido", (string)null);
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.CategoriaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_categoria_item");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_categoria_item_codigo");

                    b.ToTable("categoria_item", (string)null);
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Admissao")
                        .HasColumnType("date")
                        .HasColumnName("admissao");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("area");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cargo_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Drt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("drt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id")
                        .HasName("pk_colaborador");

                    b.HasIndex("CargoId")
                        .HasDatabaseName("ix_colaborador_cargo_id");

                    b.HasIndex("Drt")
                        .IsUnique()
                        .HasDatabaseName("ix_colaborador_drt");

                    b.HasIndex("UnidadeId")
                        .HasDatabaseName("ix_colaborador_unidade_id");

                    b.ToTable("colaborador", (string)null);
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.Entrega", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssinaturaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("assinatura_url");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("colaborador_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora");

                    b.Property<Guid?>("EntregaOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("entrega_origem_id");

                    b.Property<Guid>("FacilitadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("facilitador_id");

                    b.Property<Guid>("MotivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("motivo_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_movimentacao");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id")
                        .HasName("pk_entrega");

                    b.HasIndex("ColaboradorId")
                        .HasDatabaseName("ix_entrega_colaborador_id");

                    b.HasIndex("DataHora")
                        .HasDatabaseName("ix_entrega_data_hora");

                    b.HasIndex("EntregaOrigemId")
                        .HasDatabaseName("ix_entrega_entrega_origem_id");

                    b.HasIndex("FacilitadorId")
                        .HasDatabaseName("ix_entrega_facilitador_id");

                    b.HasIndex("MotivoId")
                        .HasDatabaseName("ix_entrega_motivo_id");

                    b.HasIndex("UnidadeId")
                        .HasDatabaseName("ix_entrega_unidade_id");

                    b.ToTable("entrega", (string)null);
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.EntregaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("EntregaId")
                        .HasColumnType("uuid")
                        .HasColumnName("entrega_id");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("numero_serie");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("Tamanho")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tamanho");

                    b.Property<DateOnly?>("ValidadeCalculada")
                        .HasColumnType("date")
                        .HasColumnName("validade_calculada");

                    b.HasKey("Id")
                        .HasName("pk_entrega_item");

                    b.HasIndex("EntregaId")
                        .HasDatabaseName("ix_entrega_item_entrega_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_entrega_item_item_id");

                    b.ToTable("entrega_item", (string)null);
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.EventoSolicitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("responsavel");

                    b.Property<Guid>("SolicitacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitacao_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_evento_solicitacao");

                    b.HasIndex("SolicitacaoId")
                        .HasDatabaseName("ix_evento_solicitacao_solicitacao_id");

                    b.ToTable("evento_solicitacao", (string)null);
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.ItemEpiEpc", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("NumeroCa")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_ca");

                    b.Property<bool>("PossuiTamanho")
                        .HasColumnType("boolean")
                        .HasColumnName("possui_tamanho");

                    b.Property<int?>("ValidadePadraoMeses")
                        .HasColumnType("integer")
                        .HasColumnName("validade_padrao_meses");

                    b.HasKey("Id")
                        .HasName("pk_item_epi_epc");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_item_epi_epc_categoria_id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_item_epi_epc_codigo");

                    b.ToTable("item_epi_epc", (string)null);
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("acao");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("DadosAntes")
                        .HasColumnType("text")
                        .HasColumnName("dados_antes");

                    b.Property<string>("DadosDepois")
                        .HasColumnType("text")
                        .HasColumnName("dados_depois");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entidade");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidade_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_log_auditoria");

                    b.HasIndex("DataHora")
                        .HasDatabaseName("ix_log_auditoria_data_hora");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_log_auditoria_usuario_id");

                    b.ToTable("log_auditoria", (string)null);
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.MotivoMovimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.Property<bool>("SemDevolucao")
                        .HasColumnType("boolean")
                        .HasColumnName("sem_devolucao");

                    b.Property<string>("TipoAplicavel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_aplicavel");

                    b.HasKey("Id")
                        .HasName("pk_motivo_movimentacao");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_motivo_movimentacao_codigo");

                    b.ToTable("motivo_movimentacao", (string)null);
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.Solicitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Assinatura")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assinatura");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("colaborador_id");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criada_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("EntregaId")
                        .HasColumnType("uuid")
                        .HasColumnName("entrega_id");

                    b.PrimitiveCollection<List<string>>("Fotos")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("fotos");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<DateOnly?>("MaterialDataEntrega")
                        .HasColumnType("date")
                        .HasColumnName("material_data_entrega");

                    b.Property<string>("MaterialFabricacao")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("material_fabricacao");

                    b.Property<string>("MaterialLote")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("material_lote");

                    b.Property<string>("MaterialMarca")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("material_marca");

                    b.Property<Guid>("MotivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("motivo_id");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("protocolo");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("Relato")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("relato");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Tamanho")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tamanho");

                    b.HasKey("Id")
                        .HasName("pk_solicitacao");

                    b.HasIndex("ColaboradorId")
                        .HasDatabaseName("ix_solicitacao_colaborador_id");

                    b.HasIndex("CriadaEm")
                        .HasDatabaseName("ix_solicitacao_criada_em");

                    b.HasIndex("EntregaId")
                        .HasDatabaseName("ix_solicitacao_entrega_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_solicitacao_item_id");

                    b.HasIndex("MotivoId")
                        .HasDatabaseName("ix_solicitacao_motivo_id");

                    b.HasIndex("Protocolo")
                        .IsUnique()
                        .HasDatabaseName("ix_solicitacao_protocolo");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_solicitacao_status");

                    b.ToTable("solicitacao", (string)null);
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.Unidade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sigla");

                    b.HasKey("Id")
                        .HasName("pk_unidade");

                    b.ToTable("unidade", (string)null);
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("perfil");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_email");

                    b.HasIndex("UnidadeId")
                        .HasDatabaseName("ix_usuario_unidade_id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.CargoItemPermitido", b =>
                {
                    b.HasOne("GestaoEpiEpc.Domain.Entities.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cargo_item_permitido_cargo_cargo_id");

                    b.HasOne("GestaoEpiEpc.Domain.Entities.ItemEpiEpc", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cargo_item_permitido_item_epi_epc_item_id");

                    b.Navigation("Cargo");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.Colaborador", b =>
                {
                    b.HasOne("GestaoEpiEpc.Domain.Entities.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_colaborador_cargo_cargo_id");

                    b.HasOne("GestaoEpiEpc.Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_colaborador_unidade_unidade_id");

                    b.Navigation("Cargo");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.Entrega", b =>
                {
                    b.HasOne("GestaoEpiEpc.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entrega_colaborador_colaborador_id");

                    b.HasOne("GestaoEpiEpc.Domain.Entities.Entrega", "EntregaOrigem")
                        .WithMany()
                        .HasForeignKey("EntregaOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_entrega_entrega_entrega_origem_id");

                    b.HasOne("GestaoEpiEpc.Domain.Entities.Usuario", "Facilitador")
                        .WithMany()
                        .HasForeignKey("FacilitadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entrega_usuario_facilitador_id");

                    b.HasOne("GestaoEpiEpc.Domain.Entities.MotivoMovimentacao", "Motivo")
                        .WithMany()
                        .HasForeignKey("MotivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entrega_motivo_movimentacao_motivo_id");

                    b.HasOne("GestaoEpiEpc.Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entrega_unidade_unidade_id");

                    b.Navigation("Colaborador");

                    b.Navigation("EntregaOrigem");

                    b.Navigation("Facilitador");

                    b.Navigation("Motivo");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.EntregaItem", b =>
                {
                    b.HasOne("GestaoEpiEpc.Domain.Entities.Entrega", "Entrega")
                        .WithMany("Itens")
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entrega_item_entrega_entrega_id");

                    b.HasOne("GestaoEpiEpc.Domain.Entities.ItemEpiEpc", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entrega_item_item_epi_epc_item_id");

                    b.Navigation("Entrega");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.EventoSolicitacao", b =>
                {
                    b.HasOne("GestaoEpiEpc.Domain.Entities.Solicitacao", "Solicitacao")
                        .WithMany("Historico")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evento_solicitacao_solicitacao_solicitacao_id");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.ItemEpiEpc", b =>
                {
                    b.HasOne("GestaoEpiEpc.Domain.Entities.CategoriaItem", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_item_epi_epc_categoria_item_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.LogAuditoria", b =>
                {
                    b.HasOne("GestaoEpiEpc.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_log_auditoria_usuario_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.Solicitacao", b =>
                {
                    b.HasOne("GestaoEpiEpc.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_solicitacao_colaborador_colaborador_id");

                    b.HasOne("GestaoEpiEpc.Domain.Entities.Entrega", "Entrega")
                        .WithMany()
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_solicitacao_entrega_entrega_id");

                    b.HasOne("GestaoEpiEpc.Domain.Entities.ItemEpiEpc", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_solicitacao_item_epi_epc_item_id");

                    b.HasOne("GestaoEpiEpc.Domain.Entities.MotivoMovimentacao", "Motivo")
                        .WithMany()
                        .HasForeignKey("MotivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_solicitacao_motivo_movimentacao_motivo_id");

                    b.Navigation("Colaborador");

                    b.Navigation("Entrega");

                    b.Navigation("Item");

                    b.Navigation("Motivo");
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("GestaoEpiEpc.Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_unidade_unidade_id");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.Entrega", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("GestaoEpiEpc.Domain.Entities.Solicitacao", b =>
                {
                    b.Navigation("Historico");
                });
#pragma warning restore 612, 618
        }
    }
}
